### PR TITLE
[Chatterbox] add support for iswap commands

### PR DESCRIPTION
**Pull request by DonSqualo**

### CODE REVIEW

**Comment by ben-ray** [comment]
based additions to plr

**Comment by rickwierenga** [comment]
The ChatterBoxBackend is supposed to be a hardware-agnostic dummy backend for all liquid handlers.

Perhaps we can subclass ChatterBox into Chatstar/Chatster which adds STAR-specific functionalities?

**Comment by DonSqualo** [comment]
> The ChatterBoxBackend is supposed to be a hardware-agnostic dummy backend for all liquid handlers.
> 
> Perhaps we can subclass ChatterBox into Chatstar/Chatster which adds STAR-specific functionalities?

I was wondering the same. But why not have chatterbox support all liquid handlers then? I kind of think it should be completely hardware agnostic by always working

**Comment by rickwierenga** [comment]
I think supporting all possible methods any backend is going to define in this single ChatterBoxBackend will be messy, and potentially undoable if there is a naming conflict between methods. I prefer to have one chattering backend for each robot.

**Comment by DonSqualo** [comment]
refactored.
Why is CI failing?

**Comment by rickwierenga** [comment]
Thanks!

**Pull request merged**
