### PR TITLE
Updating the Opentrons temperature control module

### PR DESCRIPTION
**Pull request by lennijusten**
Checking in work so that @rickwierenga can see/review progress.

### CODE REVIEW

**Comment by lennijusten** [comment]
Still todo:
- Allow users to specify which aluminum block plate sits atop the temp control module
- Test the implementation!

**Comment by lennijusten** [comment]
@rickwierenga I updated the PR to instead get the aluminum tube racks from the [Opentrons shared data](https://github.com/Opentrons/opentrons/tree/26929a2d92715ab23d7a4832f2548a2bab565d11/shared-data/labware/definitions/2). 

I also added a `tube_rack` arg to the `OpentronsTemperatureModuleV2`. By default, this is `None` indicating no tube rack on the temp controller module.

**Comment by lennijusten** [comment]
Do you see anything obvious that still needs to be done here? I'll hopefully be able to test in the lab later this week.

**Comment by rickwierenga** [comment]
> I updated the PR to instead get the aluminum tube racks from the [Opentrons shared data](https://github.com/Opentrons/opentrons/tree/26929a2d92715ab23d7a4832f2548a2bab565d11/shared-data/labware/definitions/2).

nice!

> Do you see anything obvious that still needs to be done here? I'll hopefully be able to test in the lab later this week.

I think you should be slightly careful when testing, as the resource definition might differ from what I manually calibrated before. Probably best to not use real bacteria while testing.

**Pull request merged**
