### PR TITLE
document cmm

### PR DESCRIPTION
**Pull request by rickwierenga**
#69

### CODE REVIEW

**Comment by BioCam** [comment]
Shall we get the new and upgraded probing functions from PR260 into PR and then get on the documentation with the updated versions?

**Comment by rickwierenga** [comment]
the z-probing from 260 can be a new section in this notebook. I hope to merge 260 next week now that my robot is free of <>, at which point we could update this notebook. should we block this on that pr, or merge now and update later?

**Comment by rickwierenga** [comment]
todo reminder: put Camillo's video in the doc

**Comment by rickwierenga** [comment]
@BioCam i updated with #260 and your video. what do you think?

**Comment by BioCam** [comment]
This looks fantastic!

I think...
- the last link to mapping a 3D surface is not working?
- we can hyperlink the clld_probing video to the clld_probing section for visualisation purposes. Is it possible to embed the YouTube video directly?
(haven't tried it yet)

**Comment by rickwierenga** [comment]
> the last link to mapping a 3D surface is not working?

That should be fixed when rendered into html. MyST-NB uses a slightly different format than normal/github jupyter notebooks for hyperlinks.

> we can hyperlink the clld_probing video to the clld_probing section for visualisation purposes. Is it possible to embed the YouTube video directly?

Yes, already embedded! Just not rendered by GitHub, but will be rendered if you `make docs` locally :)

https://github.com/PyLabRobot/pylabrobot/pull/290/files#diff-20abf20190ef22190a8bb002eedd1bd832ccc1e71ca05586403c2f39a7932adfR232

image

**Pull request merged**
