### PR TITLE
[plate_carriers] fix parameters of flex plate carriers

### PR DESCRIPTION
**Pull request by jkhales**

### CODE REVIEW

**Comment by rickwierenga** [comment]
Where did you get these from? I got the existing definitions from our VENUS labware library.

**Comment by ben-ray** [comment]
Ooh you are right - we should repeat this using your new multiflex carrier tool. I previously thought L5FLEX carriers referred to multiflex carriers, but these must be some other resource we don't have in our lab. We'll update this PR with definitions from your multiflex carrier tool

**Comment by ben-ray** [comment]
I used the Labware Assistant 3D tool from Hamilton [here](https://download.hamiltonsupport.com/wl/?id=VQY0XAzTfcT7KY29A1YJtZVFwZ7GMOO2&path=Hamilton%20GUIs%20and%20Tools%2FMultiflexCarrierAssistantv4.10.zip&mode=grid&download=1) to build & save these multiflex configurations (MFX_CAR_5MTP HPTab.tml and MFX_CAR_5DWP HPTab.tml), then used @rickwierenga's [make_flexcarriers.py](https://github.com/PyLabRobot/pylabrobot/blob/main/tools/make_resources/ham/make_flexcarriers.py) like this:

```
from tools.make_resources.ham.make_flexcarriers import make_from_file
from tools.make_resources.maker import make

BASE_DIR = "C:\\Program Files (x86)\\HAMILTON\\LabWare\\ML_STAR\\MultiFlexCarrier"

OUT_FILE = "MFX_CAR_5DWP_HPTab.py"
make(base_dir=BASE_DIR,
     out_file=OUT_FILE,
     pattern=r'MFX_CAR_5DWP [\S_]+.tml',
     make_from_file = make_from_file)

OUT_FILE = "MFX_CAR_5MTP_HPTab.py"
make(base_dir=BASE_DIR,
     out_file=OUT_FILE,
     pattern=r'MFX_CAR_5MTP [\S_]+.tml',
     make_from_file = make_from_file)
```

and added the generated objects to [plate_carriers.py](https://github.com/PyLabRobot/pylabrobot/blob/main/pylabrobot/resources/ml_star/plate_carriers.py)

Not sure how to commit my changes without edit access to @jkhales fork but here is what I added:

```
def MFX_CAR_5DWP_HPTab(name: str) -> MFXCarrier:
    """ """
    return MFXCarrier(
        name=name,
        size_x=135.0,
        size_y=497.0,
        size_z=130.0,
        sites=create_homogeneous_carrier_sites(
            [
                Coordinate(x=4.0, y=-62.0, z=112.0),
                Coordinate(x=4.0, y=-62.0, z=112.0),
                Coordinate(x=4.0, y=-62.0, z=112.0),
                Coordinate(x=4.0, y=-62.0, z=112.0),
            ],
            site_size_x=127.0,
            site_size_y=86.0,
        ),
        model="MFX_CAR_5DWP HPTab",
    )


def MFX_CAR_5MTP_HPTab(name: str) -> MFXCarrier:
    """ """
    return MFXCarrier(
        name=name,
        size_x=135.0,
        size_y=497.0,
        size_z=130.0,
        sites=create_homogeneous_carrier_sites(
            [
                Coordinate(x=4.0, y=-62.0, z=112.0),
                Coordinate(x=4.0, y=-62.0, z=112.0),
                Coordinate(x=4.0, y=-62.0, z=112.0),
                Coordinate(x=4.0, y=-62.0, z=112.0),
            ],
            site_size_x=127.0,
            site_size_y=86.0,
        ),
        model="MFX_CAR_5MTP HPTab",
    )
```

You can revert those changes from L5FLEX, I was mistaken. These are not multiflex carriers. The new ones I have added should be correct.

**Comment by jkhales** [comment]
> I used the Labware Assistant 3D tool from Hamilton [here](https://download.hamiltonsupport.com/wl/?id=VQY0XAzTfcT7KY29A1YJtZVFwZ7GMOO2&path=Hamilton%20GUIs%20and%20Tools%2FMultiflexCarrierAssistantv4.10.zip&mode=grid&download=1) to build & save these multiflex configurations (MFX_CAR_5MTP HPTab.tml and MFX_CAR_5DWP HPTab.tml), then used @rickwierenga's [make_flexcarriers.py](https://github.com/PyLabRobot/pylabrobot/blob/main/tools/make_resources/ham/make_flexcarriers.py) like this:
> 
> ```
> from tools.make_resources.ham.make_flexcarriers import make_from_file
> from tools.make_resources.maker import make
> 
> BASE_DIR = "C:\\Program Files (x86)\\HAMILTON\\LabWare\\ML_STAR\\MultiFlexCarrier"
> 
> OUT_FILE = "MFX_CAR_5DWP_HPTab.py"
> make(base_dir=BASE_DIR,
>      out_file=OUT_FILE,
>      pattern=r'MFX_CAR_5DWP [\S_]+.tml',
>      make_from_file = make_from_file)
> 
> OUT_FILE = "MFX_CAR_5MTP_HPTab.py"
> make(base_dir=BASE_DIR,
>      out_file=OUT_FILE,
>      pattern=r'MFX_CAR_5MTP [\S_]+.tml',
>      make_from_file = make_from_file)
> ```
> 
> and added the generated objects to [plate_carriers.py](https://github.com/PyLabRobot/pylabrobot/blob/main/pylabrobot/resources/ml_star/plate_carriers.py)
> 
> Not sure how to commit my changes without edit access to @jkhales fork but here is what I added:
> 
> ```
> def MFX_CAR_5DWP_HPTab(name: str) -> MFXCarrier:
>     """ """
>     return MFXCarrier(
>         name=name,
>         size_x=135.0,
>         size_y=497.0,
>         size_z=130.0,
>         sites=create_homogeneous_carrier_sites(
>             [
>                 Coordinate(x=4.0, y=-62.0, z=112.0),
>                 Coordinate(x=4.0, y=-62.0, z=112.0),
>                 Coordinate(x=4.0, y=-62.0, z=112.0),
>                 Coordinate(x=4.0, y=-62.0, z=112.0),
>             ],
>             site_size_x=127.0,
>             site_size_y=86.0,
>         ),
>         model="MFX_CAR_5DWP HPTab",
>     )
> 
> 
> def MFX_CAR_5MTP_HPTab(name: str) -> MFXCarrier:
>     """ """
>     return MFXCarrier(
>         name=name,
>         size_x=135.0,
>         size_y=497.0,
>         size_z=130.0,
>         sites=create_homogeneous_carrier_sites(
>             [
>                 Coordinate(x=4.0, y=-62.0, z=112.0),
>                 Coordinate(x=4.0, y=-62.0, z=112.0),
>                 Coordinate(x=4.0, y=-62.0, z=112.0),
>                 Coordinate(x=4.0, y=-62.0, z=112.0),
>             ],
>             site_size_x=127.0,
>             site_size_y=86.0,
>         ),
>         model="MFX_CAR_5MTP HPTab",
>     )
> ```
> 
> You can revert those changes from L5FLEX, I was mistaken. These are not multiflex carriers. The new ones I have added should be correct.

oh nice. I'm a bit suspicious of these since the z values are equal on each, but they are not equal on the physical carrier.

Perhaps we need to find the APE_CARRIER files themselves? It seems like this was attempted and aborted previously [here](https://forums.pylabrobot.org/t/how-can-i-pick-up-standard-tips-from-ape-carrier-on-hamilton-star/531) I couldn't find them on either of our computers though 😞 Any ideas about where I could find them?

**Comment by jkhales** [comment]
Closing this after discussing with @ben-ray and not being able to resolve the above questions about the z values:

**Comment by ben-ray** [comment]
[this is new](https://docs.pylabrobot.org/resources/hamilton_parse.html)
Rick shipped it today but we didn't pull before our attempt. see [here](https://github.com/PyLabRobot/pylabrobot/commit/a85c6d5169960ecf87bacc6da33cb47c940f2880)

**Pull request closed without merging**
