### PR TITLE
hamilton liquid classes make kwargs

### PR DESCRIPTION
**Pull request by rickwierenga**

### CODE REVIEW

**Comment by rickwierenga** [comment]
[more obvious link to the original issue](https://github.com/PyLabRobot/pylabrobot/issues/225)

new behavior:

```python
>>> from pylabrobot.liquid_handling.liquid_classes.hamilton.star import StandardVolumeFilter_Water_DispenseSurface
>>> hlc = StandardVolumeFilter_Water_DispenseSurface
>>> hlc.make_asp_kwargs(num_channels=2)
{'flow_rates': [100.0, 100.0], 'mix_speed': [100.0, 100.0], 'transport_air_volume': [5.0, 5.0], 'blow_out_air_volume': [0.0, 0.0], 'swap_speed': [2.0, 2.0], 'settling_time': [1.0, 1.0], 'clot_detection_height': [0.0, 0.0]}
>>> hlc.make_asp96_kwargs()
{'flow_rate': 100.0, 'mix_speed': 100.0, 'transport_air_volume': 5.0, 'blow_out_air_volume': 0.0, 'swap_speed': 2.0, 'settling_time': 1.0}
```

can be used like

```python
await lh.aspirate(..., **hlc.make_asp_kwargs(3))
```

⚠️ backends no longer automatically find these values ⚠️

**Comment by rickwierenga** [comment]
for volume correction using the curve:

```python
>>> hlc.compute_corrected_volume(42)
46.593333333333334
```

**Comment by BioCam** [comment]
> ```python
> corrected_volume = hlc.compute_corrected_volume(42)
> await lh.aspriate(..., vols=[corrected_volume])
> ```

How does this deal with multi-channels, i.e. lists of volumes?

Does this mean the corrected_volume has to be handed to the aspirate function directly?

**Comment by rickwierenga** [comment]
> How does this deal with multi-channels, i.e. lists of volumes?

It's still just a list of floats. different ways to handle it, eg:

```py
corrected_volumes = [hlc.compute_corrected_volume(x) for x in [42, 21]]
await lh.aspirate(..., vols=corrected_volumes)
```

> Does this mean the corrected_volume has to be handed to the aspirate function directly?

yes

**Comment by BioCam** [comment]
Does this mean the previous handling of HamiltonLiquidClass is completely absolute with this PR?
i.e. all protocols developed in PLR are now not functional anymore?

Can you please elaborate on this?
```python
await lh.aspirate(..., vols=corrected_volumes)
```
What does a complete aspiration dispensation procedure look like?

I didn't like the HamiltonLiquidClass either but I am wondering what is the advantage of this much longer implementation?

**Comment by rickwierenga** [comment]
> Does this mean the previous handling of HamiltonLiquidClass is completely absolute with this PR?

The previous automatic handling of liquid classes was removed.

If you use liquid classes, as do we, there is simply a new api for them: instead of passing `hlc=something`, you use `**hlc.make_asp_kwargs()`, to preserve the parameter sets people have already created.

> What does a complete aspiration dispensation procedure look like?

It depends on whether you want to use a liquid class, or specify parameters yourself, or take backend defaults.

1. use a liquid class

```python
from pylabrobot.liquid_handling.liquid_classes.hamilton.star import StandardVolumeFilter_Water_DispenseSurface
hlc = StandardVolumeFilter_Water_DispenseSurface
corrected_volumes = [hlc.compute_corrected_volume(x) for x in [42, 21]]
await lh.aspirate(some_wells, vols=corrected_volumes, **hlc.make_asp_kwargs(2))
```

2. specify yourself

```python
def my_correction_curve(x): return x + 1
corrected_volumes = [my_correction_curve(x) for x in [42, 21]]
await lh.aspirate(some_wells, vols=corrected_volumes, flow_rates=[21, 21], mix_speed=[1, 1]) # etc.
```

3. use backend default

```python
await lh.aspirate(some_wells, vols=[42, 21])
```

> I didn't like the HamiltonLiquidClass either but I am wondering what is the advantage of this much longer implementation?

In PLR, the implementation is much shorter and simpler. This PR removed 198 lines of code. Before, we had four sources of values, in order or precedence:
1. user specified
2. user specified liquid class
3. automatically inferred liquid class
4. backend default

Now it's all user-specified (either explicitly or through hlc.make_asp_kwargs()), or the backend gives a default.

Had the liquid classes been accurate, this would have been nice. But users still needed to fine tune their liquid transfers, and so the automatic handling does not make a substantial difference.

Another benefit is the code is now explicit. Before, the behavior was hidden and not obvious. (for example, when aspirating 100uL twice and dispensing 200uL, the dispensing drive would not reset, because the correction curve is non linear, so `2*f(100)!=f(2*100)`.

**Pull request merged**
