### PR TITLE
Adaptive lh.summary()

### PR DESCRIPTION
**Pull request by BioCam**
Hi everyone,

This is a small PR to make the `lh.summary()` method for Hamilton STAR decks...
1. adaptive to the length of resources on the deck,
2. return nested information on carrier sites (as opposed to just information about the carrier site itself)

----

## Summary of the issue

`lh.summary` is a very useful little function that returns the "deck tree", a visual representation of the resources on the deck and their child-parent relationship.
This is particularly useful because the PLR visualizer is currently not supporting 3D visualization, and therefore does not provide information about stacked/nested resources but only shows the top resources in the z-dimension.

However, there are 2 issues with `lh.summary`:
1. if the name of a resource is long it will distort the layout of the deck tree string that `lh.summary` returns,
2. if a resource is not directly placed on a `CarrierSite` it is not visible in the `lh.summary` deck tree; e.g. if one adds a temperature control module (such as a Hamilton Heater-Cooler [HHC]) onto the `CarrierSite` of a shaker carrier, and then adds a plate on the HHC, then the plate is currently not visible in the deck tree.

I created this completely imaginary deck layout to highlight this problem:

old_summary

## PR content

I modified the `HamiltonDeck.summary()` method in `pylabrobot/resources/hamilton/HamiltonDecks.py` to...
1. enable self-adjustment of the "Resource" column of the deck tree based on the longest line inside that column,
2. enable the visualization of all nested resources on a `CarrierSite` up to and not including resources of type `{"well", "tube", "tip_spot"}` (otherwise the deck tree would show all wells of all plates, tips of tipracks, etc)

The exact same imaginary deck layout showcased above now returns:

image

This gives a true account of the deck layout.

**Technical details**
1. The maximal length of a line in the resource column is calculated using a new helper function called `depth_first_search`
 which uses a self-implemented DFS algorithm to quickly traverse the entire deck tree data structure.
2. a new `parse_site` helper function parses through individual `CarrierSite`s until it reaches either a resource that has no child_resource or where the child_resource is of type `{"well", "tube", "tip_spot"}`. Importantly, this function has "foresight", i.e. checks whether a potential child_resource (if it exists) is empty, giving crucial information about where an operator could still place a new resource to maximise deck utility.

NB.: This enables super simple parsing of the `lh.summary()` deck tree string ... if one is interested in this 👀 

## Next Steps

Please give feedback when using it on the myriad of different deck layouts people create. Let's optimise via iteration :)

### CODE REVIEW

**Comment by rickwierenga** [comment]
Nice work making this more generalizable.

2 small initial comments:
- It seems that your new version would also print out the CarrierSite for normal carriers. Although technically accurate, perhaps this is not needed, and this method is supposed to be very user-focussed.
- Only the children of CarrierSite are printed. If a non-CarrierSite resource has children, it seems they are not printed.

I can imagine both being by design, but perhaps it's worth considering changing.

> NB.: This enables super simple parsing of the lh.summary() deck tree string ... if one is interested in this 👀

I honestly don't understand why anyone would want to go from "PLR resource info" (memory) > string > something else in memory.

**Comment by BioCam** [comment]
> * It seems that your new version would also print out the CarrierSite for normal carriers. Although technically accurate, perhaps this is not needed, and this method is supposed to be very user-focussed.

I don't think this is correct. The _name_ of a CarrierSite is not printed as a return from `lh.summary`.
It is printed as a return from the helper function `depth_first_search` because it made the DSF algorithm implementation a lot easier. However, `depth_first_search` is only used to identify how much space is supposed to be allocated before constructing the column for the final output, it is never returned because, I agree with you, `lh.summary` should not included the unnecessary names of the CarrierSite.



> * Only the children of CarrierSite are printed. If a non-CarrierSite resource has children, it seems they are not printed.

Do you mean that if a resource is a direct child of `lh.deck` then it's children are not printed?
If so, then yes you are correct, I did not modify the status quo of `lh.deck` that are not `Carrier`s.

**Comment by BioCam** [comment]
This does the job, exemplified by placing a heater-cooler onto the deck by itself:

```python
hhc_1 = Hamilton_HC(name="lonely_hhc")
lh.deck.assign_child_resource(hhc_1, location=Coordinate(100+6*22.5,100,100))
```

image

**Comment by BioCam** [comment]
Corrected subresource presentation for `Trash` and `Container`:

image

**Comment by rickwierenga** [comment]
summary of changes:
- moved to a more native approach with the DFSs, just counts the name length instead of creating strings first.
- define `rail_column_length`, `name_column_length`, etc. which are used for string padding instead of the crazy arithmetic we had earlier
- have two resource parsers right now: `parse_resource` (general) and `parse_carrier_site`. can easily add more. for specialized resource->string row parsing.

**Comment by rickwierenga** [comment]
feels good to get rid of this legacy code in HamiltonDeck.summary 😅 as you saw, the location of resources on carrier sites was actually that of A1. A relic from venus!

**Comment by rickwierenga** [comment]
> `hhc_1 = Hamilton_HC(name="lonely_hhc")`
> `lh.deck.assign_child_resource(hhc_1, location=Coordinate(100+6*22.5,100,100))`

is `Hamilton_HC` a proprietary module? ;)

**Comment by BioCam** [comment]
> > `hhc_1 = Hamilton_HC(name="lonely_hhc")`
> > `lh.deck.assign_child_resource(hhc_1, location=Coordinate(100+6*22.5,100,100))`
> 
> is `Hamilton_HC` a proprietary module? ;)

hahaha, not at all 😅 

But if I remember correctly, we had a discussion on how to integrate the physical definition of machines like heater-shakers and temperature control machines directly into the front end.

I haven't found the time yet to look more into how to change these frontends:
At the moment they simply take: `front_end(backend=backend, size_x, size_y, size_z)`, I believe.

I would like to change this to `front_end(backend=backend, model=MFXModule_instance)`

That way people can still use the MFXModule_instance as a standard `MFXModule`, i.e. a plate holder, even if the backend isn't ready/not working/not needed; plus it means we can work on integration of these new machines in parallel (backend // physical_definition).

Happy to discuss this some more :)

**Comment by rickwierenga** [comment]
think it's fixed:

```
Rail  Resource                                                      Type           Coordinates (mm)
=================================================================================================================
(-13) ├── trash_core96                                              Trash          (-232.100, 110.300, 189.000)
      │
(-3)  ├── x                                                         Container      (000.000, 000.000, 000.000)
      │   ├── child with a really really really really long name    Container      (000.000, 000.000, 000.000)
      │
(1)   ├── tip_carrier                                               TipCarrier     (100.000, 063.000, 100.000)
      │   ├── tip_rack_01                                           TipRack        (106.200, 073.000, 214.950)
      │   ├── tip_rack_02                                           TipRack        (106.200, 169.000, 214.950)
      │   ├── <empty>
      │   ├── tip_rack_04                                           TipRack        (106.200, 361.000, 214.950)
      │   ├── <empty>
      │
(7)   ├── mfx_carrier                                               MFXCarrier     (235.000, 063.000, 100.000)
      │   ├── empty thing                                           MFXModule      (235.000, 068.000, 118.195)
      │   │   ├── <empty>
      │   ├── mfx_tip_module                                        MFXModule      (235.000, 164.000, 118.195)
      │   │   ├── new_tip_rack                                      TipRack        (241.200, 169.000, 214.800)
      │   ├── <empty>
      │   ├── <empty>
      │   ├── <empty>
      │
(21)  ├── plate carrier                                             PlateCarrier   (550.000, 063.000, 100.000)
      │   ├── aspiration plate                                      Plate          (554.000, 071.500, 186.150)
      │   ├── <empty>
      │   ├── dispense plate                                        Plate          (554.000, 263.500, 186.150)
      │   ├── <empty>
      │   ├── <empty>
```

can you confirm?

> Happy to discuss this some more :)

A separate discussion indeed :) Let's have it soon.

**Comment by BioCam** [comment]
Unfortunately, still quite off after merging to the latest version, though I'm not sure why

image

**Comment by rickwierenga** [comment]
That is very strange.

Where is the `summary` function from in your code?

**Comment by BioCam** [comment]
Copied out of the updated `hamilton_decks.py` to investigate what might be going on

Same for standard `lh.summary()`

image

**Comment by rickwierenga** [comment]
could you share/email your deck layout? im curious to see if i can reproduce this

**Comment by BioCam** [comment]
The deck is completely invented with no purpose so theoretically I could, but practically I cannot share the exact same one because of the all the MFXModules I created myself that are on it.

I rewrote it to only include resources that are already in the PLR Resource Library, and it still shows the same behaviour:

Deck for reproduction:

```python
# Generate PLATE & MFX carrier instances
mfx_carrier_1 = MFX_CAR_L5_base(name='mfx_carrier_1')
mfx_carrier_2 = MFX_CAR_L5_base(name='mfx_carrier_2')
shaker_carrier_1 = PLT_CAR_L4_SHAKER(name='shaker_carrier_1')

# Assign plate carriers to deck
lh.deck.assign_child_resource(mfx_carrier_1, rails=8)
lh.deck.assign_child_resource(mfx_carrier_2, rails=25)
lh.deck.assign_child_resource(shaker_carrier_1, rails=1)

# MFX Modules
mfx_carrier_1[0] = DWP_module_1 = MFX_DWP_rackbased_module(name="DWP_module_1")
mfx_carrier_1[1] = DWP_module_2 = MFX_DWP_rackbased_module(name="DWP_module_2")

mfx_carrier_2[0] = LowP_module_1 = MFX_DWP_rackbased_module(name="DWP_module_3")
mfx_carrier_2[1] = LowP_module_2 = MFX_DWP_rackbased_module(name="DWP_module_4")
mfx_carrier_2[2] = LowP_module_3 = MFX_DWP_rackbased_module(name="DWP_module_5")
mfx_carrier_2[3] = LowP_module_4 = MFX_DWP_rackbased_module(name="DWP_module_6")
mfx_carrier_2[4] = LowP_module_5 = MFX_DWP_rackbased_module(name="MFX_module_with_a_really_long_name MFX_module_with_a_really_long_name")

Alpaqua_magnum_flx1 = Alpaqua_96_magnum_flx(name="Alpaqua_magnum_flx1")
LowP_module_2.assign_child_resource(Alpaqua_magnum_flx1)
Alpaqua_magnum_flx2 = Alpaqua_96_magnum_flx(name="Alpaqua_magnum_flx2")
LowP_module_2.assign_child_resource(Alpaqua_magnum_flx2)
Alpaqua_magnum_flx3 = Alpaqua_96_magnum_flx(name="Alpaqua_magnum_flx3")
LowP_module_2.assign_child_resource(Alpaqua_magnum_flx3)

# Plate assignment
Cos_96_Rd_1 = Cos_96_Rd(name=f"Cos_96_Rd_1")
Porvair_6_reservoir_47ml_Vb_1 = Porvair_6_reservoir_47ml_Vb(name="Porvair_6_reservoir_47ml_Vb_1")

Cos_96_DWP_2mL_Vb_1 =  Cos_96_DWP_2mL_Vb(name="Cos_96_DWP_2mL_Vb_1") 
Cos_96_Rd_2 =  Cos_96_Rd(name="Cos_96_Rd_2") 
agilent_1_reservoir_290ml_1 = agilent_1_reservoir_290ml(name="agilent_1_reservoir_290ml_1")


DWP_module_1.assign_child_resource(Cos_96_Rd_1)
DWP_module_2.assign_child_resource(Porvair_6_reservoir_47ml_Vb_1)

LowP_module_1.assign_child_resource(Cos_96_DWP_2mL_Vb_1)
LowP_module_3.assign_child_resource(Cos_96_Rd_2)
LowP_module_4.assign_child_resource(agilent_1_reservoir_290ml_1)

# Generate TIP carrier instances
tip_carrier_1 = TIP_CAR_480_A00(name='tip_carrier_1')

# Assign tip carriers to deck
lh.deck.assign_child_resource(tip_carrier_1, rails=14)

tip_carrier_1[0] = STF_L(name=f'tip_300ul_00')

tip_carrier_1[1] = HTF_L(name=f'tip_1000ul_02')
tip_carrier_1[2] = HTF_L(name=f'tip_1000ul_01')
tip_carrier_1[3] = HTF_L(name=f'tip_1000ul_00')
tip_carrier_1[4] = STF_L(name=f'tip_300ul_01')
```

Produces:
image

**Comment by BioCam** [comment]
I think I found the culprit in your refactored version:

I could see that you have refactored my first deck tree computation (which represents a patchy duplication, I agree) using the following:
```python
    exclude_categories = {"well", "tube", "tip_spot", "carrier_site"} # don't print these

    def find_longest_child_name(resource: Resource, depth=0):
      """ DFS to find longest child name, and depth of that child, excluding excluded categories """
      qualified_children = [c for c in resource.children if c.category not in exclude_categories]
      if len(qualified_children) == 0:
        return len(resource.name), depth
      return max(
        (len(resource.name), depth),
        max(find_longest_child_name(child, depth+1) for child in qualified_children))

    def find_longest_type_name(resource: Resource):
      """ DFS to find the longest type name """
      qualified_children = [c for c in resource.children if c.category not in exclude_categories]
      if len(qualified_children) == 0:
        return len(resource.__class__.__name__)
      return max(
        len(resource.__class__.__name__),
        max(find_longest_type_name(child) for child in qualified_children))

    # Calculate the maximum lengths of the resource name and type for proper alignment
    max_name_length, depth = find_longest_child_name(self)
    max_type_length = find_longest_type_name(self)
```

I see the logic behind it and it is pretty neat ... though I haven't tested whether it uses less computation time 😅 

But there is a bug in this current version:
- The recursion in `find_longest_child_name` is stopped early because at depth=2 (depth_0=deck, depth_1=carriers, depth_2=CarrierSite, ...) your search is erroneously stopped by `exclude_categories = {"well", "tube", "tip_spot", "carrier_site"}` containing "carrier_site".
- This means the goal is to not print "carrier_site" but you don't want it to stop the recursion search early either.
- Now, if you remove "carrier_site" from `exclude_categories ` it solves the resource column self-adjustment ... kinda:
image

Two things happen:
1. "carrier_sites" are actually not printed anyway because you wrote a special condition into the handling of its class for printing in 
```python
def print_tree(resource: Resource, depth=0):
      r_summary = print_resource_line(resource, depth=depth)

      if isinstance(resource, MFXModule) and len(resource.children) == 0:
        r_summary += "\n"
        r_summary += print_empty_spot_line(depth=depth+1)

      for child in resource.children:
        if isinstance(child, CarrierSite): # <================
          r_summary += "\n"
          if child.resource is not None:
            r_summary += print_tree(child.resource, depth=depth+1) # <================
          else:
            r_summary += print_empty_spot_line(depth=depth+1)
        elif child.category not in exclude_categories:
          r_summary += "\n"
          r_summary += print_tree(child, depth=depth+1)

      return r_summary
```
-> ` if isinstance(child, CarrierSite):` -> jump straight to its `child` / `.resource`

That's very good because we can remove "carrier_site" from `exclude_categories`, still get the desired behaviour and know why.

2. We can see that the resource column actually got a lot wider. 
This is because now that I've allowed `find_longest_child_name` to include a check of the "carrier_site" name, these names are actually really really long, and even though they are not printed they still _adjust_ the resource column width in the background.
I haven't found out yet how to to remove these long names CarrierSite names can be excluded from the current version of `find_longest_child_name`.
`def summary()` has gotten quite a lot more complicated 😅

**Comment by BioCam** [comment]
This could not be seen in your test case...

```python
Rail  Resource                                                      Type           Coordinates (mm)
=================================================================================================================
(-13) ├── trash_core96                                              Trash          (-232.100, 110.300, 189.000)
      │
(-3)  ├── x                                                         Container      (000.000, 000.000, 000.000)
      │   ├── child with a really really really really long name    Container      (000.000, 000.000, 000.000)
      │
(1)   ├── tip_carrier                                               TipCarrier     (100.000, 063.000, 100.000)
      │   ├── tip_rack_01                                           TipRack        (106.200, 073.000, 214.950)
      │   ├── tip_rack_02                                           TipRack        (106.200, 169.000, 214.950)
      │   ├── <empty>
      │   ├── tip_rack_04                                           TipRack        (106.200, 361.000, 214.950)
      │   ├── <empty>
      │
(7)   ├── mfx_carrier                                               MFXCarrier     (235.000, 063.000, 100.000)
      │   ├── empty thing                                           MFXModule      (235.000, 068.000, 118.195)
      │   │   ├── <empty>
      │   ├── mfx_tip_module                                        MFXModule      (235.000, 164.000, 118.195)
      │   │   ├── new_tip_rack                                      TipRack        (241.200, 169.000, 214.800)
      │   ├── <empty>
      │   ├── <empty>
      │   ├── <empty>
      │
(21)  ├── plate carrier                                             PlateCarrier   (550.000, 063.000, 100.000)
      │   ├── aspiration plate                                      Plate          (554.000, 071.500, 186.150)
      │   ├── <empty>
      │   ├── dispense plate                                        Plate          (554.000, 263.500, 186.150)
      │   ├── <empty>
      │   ├── <empty>

```

...because the only long-name example here is a direct child of the deck itself.

**Comment by BioCam** [comment]
This is an updated `find_longest_child_name` that goes through a lot of length to ensure the recursion isn't stopped by "carrier_site" but at the same time excludes data from resources of category "carrier_site" from the results:

```python
def find_longest_child_name(resource: Resource, depth=0):
    """DFS to find longest child name and depth of that child, excluding excluded categories and carrier_site."""
    qualified_children = [c for c in resource.children if c.category not in exclude_categories]

    # Initialize the longest name length and depth
    longest_name_length = 0 if resource.category == "carrier_site" else len(resource.name)
    max_depth = depth if resource.category != "carrier_site" else 0

    # Recurse through the children and find the maximum name length and depth
    for child in qualified_children:
        child_length, child_depth = find_longest_child_name(child, depth + 1)
        if child.category != "carrier_site":
            if child_length > longest_name_length or (child_length == longest_name_length and child_depth > max_depth):
                longest_name_length = child_length
                max_depth = child_depth

    return longest_name_length, max_depth
```

This solves the issue of the resource column being too longer, and returns the final desired deck tree:

image

**Comment by BioCam** [comment]
I've made a mistake:
Everything from above is correct except that after removing "carrier_site" from `exclude_categories` there is no wide column problem.

That was on my end due to a typo.

This means the only modification necessary was the removal of"carrier_site" from `exclude_categories`.

**Comment by rickwierenga** [comment]
> the recursion in find_longest_child_name is stopped early because at depth=2 (depth_0=deck, depth_1=carriers, depth_2=CarrierSite, ...) your search is erroneously stopped by exclude_categories = {"well", "tube", "tip_spot", "carrier_site"} containing "carrier_site".

that was indeed the issue. Should be fixed now, based off a slight rewrite of your solution above

> This means the only modification necessary was the removal of"carrier_site" from exclude_categories.

This is not the case, because sometimes carrier_site itself has the longest name (as in the unit test), even though it's not printed.

**Comment by rickwierenga** [comment]
good to merge?

**Comment by BioCam** [comment]
> > This means the only modification necessary was the removal of"carrier_site" from exclude_categories.
> 
> This is not the case, because sometimes carrier_site itself has the longest name (as in the unit test), even though it's not printed.

haha, yeah I was trying to figure out a way around this for the last hour.
Interesting solution:

```python
exclude_categories = {"well", "tube", "tip_spot", "carrier_site"} # don't print these

def find_longest_child_name(resource: Resource, depth=0):
  """ DFS to find longest child name, and depth of that child, excluding excluded categories """
  l, d = (len(resource.name), depth) if resource.category not in exclude_categories else (0, 0)
  new_depth = depth + 1 if resource.category not in exclude_categories else depth
  print(f"resource.name:{resource.name}, l:{l}")
  return max( [(l, d)] + [find_longest_child_name(c, new_depth) for c in resource.children])
```

You are actually accessing all children, even wells, but simply set their information to `(0,0)` `if resource.category in exclude_categories` and thereby enable recursion through al children but exclusion of the results in the return statement, very neat!

Yes, `lh.summary()` is now adaptive to the length of resource names and shows complete nested resource information.

Good to merge from my end :)

Thank you, @rickwierenga!

**Comment by BioCam** [comment]
Quick question:

`hamilton_decks.py:332`
```python
def print_tree(resource: Resource, depth=0):
      r_summary = print_resource_line(resource, depth=depth)

      if isinstance(resource, MFXModule) and len(resource.children) == 0:
        r_summary += "\n"
        r_summary += print_empty_spot_line(depth=depth+1)

      for child in resource.children:
        if isinstance(child, CarrierSite): # <======== Should we not have included PlateCarrierSite here?
          r_summary += "\n"
          if child.resource is not None:
            r_summary += print_tree(child.resource, depth=depth+1)
          else:
            r_summary += print_empty_spot_line(depth=depth+1)
        elif child.category not in exclude_categories:
          r_summary += "\n"
          r_summary += print_tree(child, depth=depth+1)

      return r_summary
```

**Comment by rickwierenga** [comment]
This should not be necessary since PlateCarrierSite inherits from CarrierSite, so instances of PlateCarrierSite are also CarrierSites

**Pull request merged**
