### PR TITLE
Add "__repr__" and "print_grid" to itemized_resource to display item occupacy

### PR DESCRIPTION
**Pull request by naikymen**
…ee spots

Example output:

```
12x8 TipRack
    1  2  3  4  5  6  7  8  9  10 11 12
A:  -  -  -  -  -  -  -  -  -  -  -  -
B:  -  -  -  -  -  -  -  -  -  -  -  -
C:  -  -  -  -  -  -  -  -  -  -  -  -
D:  -  -  -  -  -  -  -  -  -  -  -  -
E:  -  -  -  -  -  -  -  -  -  -  -  -
F:  -  -  -  -  -  -  -  -  -  -  -  -
G:  -  -  -  -  -  -  -  -  -  -  -  -
H:  -  -  -  -  -  -  -  -  -  -  -  -
```

### CODE REVIEW

**Comment by rickwierenga** [comment]
I think `LETTERS` is missing

**Comment by naikymen** [comment]
> I think `LETTERS` is missing

I miss R.

**Comment by naikymen** [comment]
I don't understand what the failure is on this test: https://github.com/PyLabRobot/pylabrobot/actions/runs/9028064969/job/24807920516?pr=127

**Comment by naikymen** [comment]
How its looking now if `TipRack` defined the method:

```python
@staticmethod
  def _occupied_func(x: TipSpot):
    return "V" if x.has_tip() else "-"
```

```
TipRack(name=200ul_tip_rack_MULTITOOL 1, size_x=122, size_y=86, size_z=80, location=(020.189, 020.189, 000.000))
    1  2  3  4  5  6  7  8  9  10 11 12
A:  -  V  V  V  V  V  V  V  V  V  V  V
B:  -  V  V  V  V  V  V  V  V  V  V  V
C:  -  V  V  V  V  V  V  V  V  V  V  V
D:  V  V  V  V  V  V  V  V  V  V  V  V
E:  V  V  V  V  V  V  V  V  V  V  V  V
F:  V  V  V  V  V  V  V  V  V  V  V  V
G:  V  V  V  V  V  V  V  V  V  V  V  V
H:  V  V  V  V  V  V  V  V  V  V  V  V
12x8 TipRack
```

I think its simple enough, would you like me to add the method to TipRack?

And a "spotted" tube rack defining the method:

```
  @staticmethod
  def _occupied_func(x: TubeSpot):
    return "U" if x.has_tube() else "-"
```

```
TubeRack(name=5x16_1.5_rack 1, size_x=215, size_y=72, size_z=80, location=(150.000, 023.000, 000.000))
    1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16
A:  U  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
B:  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
C:  U  -  U  -  -  -  -  -  -  -  -  -  -  -  -  -
D:  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
E:  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
16x5 TubeRack
```

**Comment by rickwierenga** [comment]
looks good! please add this to TipRack, and TubeRack when you're ready. Perhaps you can use `T` as the type for `_occupied_func`, so it's bound to `TipSpot` for the `TipRack`.

> I don't understand what the failure is on this test: https://github.com/PyLabRobot/pylabrobot/actions/runs/9028064969/job/24807920516?pr=127
sometimes the server test fails, and i still have to take a moment to figure out why. if at least one test case ran successfully, that means that things are working. feel free to ignore this for now.

**Comment by naikymen** [comment]
> looks good! please add this to TipRack, and TubeRack when you're ready. Perhaps you can use `T` as the type for `_occupied_func`, so it's bound to `TipSpot` for the `TipRack`.

Awesome, thanks for the review!

I'm not sure I understand what you mean, I know almost nothing about typing. How do I use T in that way?

**Comment by rickwierenga** [comment]
`T` is a placeholder for the resource that is "itemized" by ItemizedResource. It is TipSpot for TipRack, Well for Plate, and Tube (soon TubeSpot) for TubeRacks. ([python docs on generics](https://docs.python.org/3/library/typing.html#generics) for background)

```diff
- def _occupied_func(x: Resource):
+ def _occupied_func(x: T):
```

**Comment by rickwierenga** [comment]
do you want to add a method to TipRack? Then this should be ready to merge!

**Comment by naikymen** [comment]
Done :)

**Comment by naikymen** [comment]
:partying_face:

**Comment by rickwierenga** [comment]
great addition! thank you!

**Pull request merged**
