### PR TITLE
Fix iswap rotation issue

### PR DESCRIPTION
**Pull request by rickwierenga**
using iswap to grip ƒrom front (or back) and put to back (or front) was putting in the wrong location before

### CODE REVIEW

**Comment by jkhales** [comment]
seems like worth figuring out why previous tests didn't catch this and fixing it

**Comment by rickwierenga** [comment]
is what i am doing

**Comment by rickwierenga** [comment]
because it is a square

**Comment by rickwierenga** [comment]
LOL

**Comment by fderop** [comment]
> because it is a square

when float rotations are added, make sure to change the test to a circle 😂

**Comment by rickwierenga** [comment]
float/continuous rotations are already supported https://github.com/PyLabRobot/pylabrobot/pull/195

**Pull request merged**
