### PR TITLE
refactor MFX carriers

### PR DESCRIPTION
**Pull request by rickwierenga**
https://discuss.pylabrobot.org/t/mfx-carrier/37

### CODE REVIEW

**Comment by rickwierenga** [comment]
most of the diff is just renaming things

**Comment by rickwierenga** [comment]
- expanded ResourceHolder (formerly ResourceHolderMixin, see #281) to include a property for the child resource
- removed `CarrierSite`, replaced with `ResourceHolder`
- `Carrier`s now store the sites in a dict instead of a list
- renamed `PlateCarrierSite` to `PlateHolder`
- `ResourceStack` and `Plate` are not longer `ResourceHolder`s, they just use `get_child_location` directly
- rename `create_homogeneous_carrier_sites` to `create_homogeneous_resources`, parameters `site_size_{x,y}` to `resource_size_{x,y}`
- rename `create_carrier_sites` to `create_resources`

**Comment by BioCam** [comment]
Going through the changes I couldn't see how the replacement of `PlateCarrierSite` to `PlateHolder` maintains the `pedestal_z_height` logic from `PlateCarrierSite`?

**Comment by rickwierenga** [comment]
PlateCarrierSite was simply renamed into PlateHolder, the implementation should be equivalent

**Pull request merged**
